[patch.crates-io]
font-types = {path="../fontations/font-types"}
read-fonts = {path="../fontations/read-fonts"}
write-fonts = {path="../fontations/write-fonts"}

[workspace]

members = [
    "fontdrasil",
    "fontbe",
    "fontir",
    "glyphs-reader",
    "glyphs2fontir",
    "ufo2fontir",
    "fontc",    
]
