[patch.crates-io]
fea-rs = {git="https://github.com/rsheeter/fea-rs.git", branch="NameId"}

[workspace]

members = [
    "fontdrasil",
    "fontbe",
    "fontir",
    "glyphs-reader",
    "glyphs2fontir",
    "ufo2fontir",
    "fontc",    
]
