# TODO remove once https://github.com/googlefonts/fontations/pull/275 in a release
[patch.crates-io]
read-fonts = { path="../fontations/read-fonts" }
write-fonts = { path="../fontations/write-fonts" }

[workspace]

members = [
    "fontdrasil",
    "fontbe",
    "fontir",
    "glyphs-reader",
    "glyphs2fontir",
    "ufo2fontir",
    "fontc",    
]
