[patch.crates-io]
read-fonts = { git="https://github.com/googlefonts/fontations.git", branch="contours" }
write-fonts = { git="https://github.com/googlefonts/fontations.git", branch="contours" }

[workspace]

members = [
    "fontdrasil",
    "fontbe",
    "fontir",
    "glyphs-reader",
    "glyphs2fontir",
    "ufo2fontir",
    "fontc",    
]
