[patch.crates-io]
read-fonts = {git="https://github.com/googlefonts/fontations.git", branch="hvar"}
write-fonts = {git="https://github.com/googlefonts/fontations.git", branch="hvar"}

[workspace]

members = [
    "fontdrasil",
    "fontbe",
    "fontir",
    "glyphs-reader",
    "glyphs2fontir",
    "ufo2fontir",
    "fontc",    
]
