[patch.crates-io]
kurbo = { git="https://github.com/linebender/kurbo.git" }

[workspace]

members = [
    "fontdrasil",
    "fontbe",
    "fontir",
    "glyphs-reader",
    "glyphs2fontir",
    "ufo2fontir",
    "fontc",    
]
