[package]
name = "glyphs-reader"
version = "0.0.1"
license = "MIT/Apache-2.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist_derive = { path = "plist_derive" }
ordered-float.workspace = true
kurbo.workspace = true

thiserror.workspace = true

log.workspace = true
env_logger.workspace = true

regex.workspace = true

chrono.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
