[package]
name = "fontc"
version = "0.0.1"
edition = "2021"
license = "MIT/Apache-2.0"
description = "A compiler for fonts."
repository = "https://github.com/googlefonts/fontmake-rs"
readme = "README.md"
categories = ["text-processing", "parsing", "graphics"]

[features]

[dependencies]
font-types = { git = 'https://github.com/googlefonts/fontations' }
read-fonts = { git = 'https://github.com/googlefonts/fontations' }
fontir = { version = "0.0.1", path = "../fontir" }
ufo2fontir = { version = "0.0.1", path = "../ufo2fontir" }
bitflags = "1.3"
serde = {version = "1.0", features = ["derive"] }
toml = "0.5.9"
bincode = "1.3.3"
filetime = "0.2.18"
clap = { version = "4.0.24", features = ["derive"] }
log = "0.4"
env_logger = "0.9.0"
thiserror = "1.0.37"

rayon = "1.6.0"

[dev-dependencies]
diff = "0.1.12"
ansi_term = "0.12.1"
tempfile = "3.3.0"
