[package]
name = "fontc"
version = "0.0.1"
edition = "2021"
license = "MIT/Apache-2.0"
description = "A compiler for fonts."
repository = "https://github.com/googlefonts/fontmake-rs"
readme = "README.md"
categories = ["text-processing", "parsing", "graphics"]

[features]

[dependencies]
fontdrasil = { version = "0.0.1", path = "../fontdrasil" }
fontbe = { version = "0.0.1", path = "../fontbe" }
fontir = { version = "0.0.1", path = "../fontir" }
glyphs2fontir = { version = "0.0.1", path = "../glyphs2fontir" }
ufo2fontir = { version = "0.0.1", path = "../ufo2fontir" }

bitflags.workspace = true
bincode.workspace = true

serde.workspace = true
serde_yaml.workspace = true

filetime.workspace = true

log.workspace = true
env_logger.workspace = true
thiserror.workspace = true

indexmap.workspace = true
regex.workspace = true

write-fonts.workspace = true

# just for fontc!
clap = { version = "4.2.1", features = ["derive"] }

rayon = "1.6.0"
crossbeam-channel = "0.5.6"

[dev-dependencies]
diff.workspace = true
ansi_term.workspace = true
tempfile.workspace = true
read-fonts.workspace = true
pretty_assertions.workspace = true
skrifa.workspace = true
kurbo.workspace = true
chrono.workspace = true